let wilaya_names: string[] = [
    "M'Sila",
    "In Guezzam",
    "Djanet",
    "Ouled Djellal",
    "Souk Ahras",
    "Ouargla",
    "Tipaza",
    "Timimoun",
    "Bordj Badji Mokhtar",
    "Oran",
    "Oum El Bouaghi",
    "Chlef",
    "Médéa",
    "Touggourt",
    "Mostaganem",
    "Béni Abbès",
    "Djelfa",
    "Saïda",
    "Tissemsilt",
    "Laghouat",
    "Relizane",
    "Tiaret",
    "El Menia",
    "Ghardaïa",
    "Tindouf",
    "Tlemcen",
    "Tizi Ouzou",
    "In Salah",
    "Biskra",
    "Sidi Bel Abbès",
    "El Tarf",
    "Aïn Témouchent",
    "Khenchela",
    "Sétif",
    "Mila",
    "Béjaïa",
    "Guelma",
    "Constantine",
    "El Oued",
    "Aïn Defla",
    "El Meghaier",
    "Mascara",
    "Tébessa",
    "Adrar",
    "Alger",
    "Skikda",
    "Bouira",
    "Bordj Bou Arreridj",
    "Naâma",
    "Tamanrasset",
    "El Bayadh",
    "Illizi",
    "Boumerdès",
    "Annaba",
    "Blida",
    "Batna",
    "Béchar",
    "Jijel"
]

wilaya_names.sort();

export default wilaya_names;